### ISSUE TITLE
Problem with ffmpeg

### ISSUE THREAD

**Issue by martinbenedict1806** [Piwigo/piwigo-videojs#103]
Hi,
i want to use the ffmpeg plugin to use the thumbnail-function in videojs. The path is correct, but the error-log of apache shows the following message:
"ffmpeg version git-2017-01-22-f1214ad Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
  configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --mandir=/usr/share/man --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=$
  libavutil      55. 44.100 / 55. 44.100
  libavcodec     57. 75.100 / 57. 75.100
  libavformat    57. 63.100 / 57. 63.100
  libavdevice    57.  2.100 / 57.  2.100
  libavfilter     6. 69.100 /  6. 69.100
  libavresample   3.  2.  0 /  3.  2.  0
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
[NULL @ 0x309d2a0] Unable to find a suitable output format for '/dev/null'
/dev/null: Invalid argument
Unable to find a suitable output format for '/dev/null'
/dev/null: Invalid argument"

i can´t find any errors in my configuration. Can anybode please help.

Regards 
Martin

**Comment by achanler** [comment]
I get the same error in my Apache log:

ffmpeg version 3.2.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
  configuration: --prefix=/usr/local --mandir=/usr/local/man --datadir=/usr/local/share/ffmpeg --pkgconfigdir=/usr/local/libdata/pkgconfig --enable-shared --enable-pic --enable-gpl --enable-postproc --enable-avfilter --enable-avresample --enable-pthreads --cc=cc --disable-indev=alsa --disable-outdev=alsa --disable-libopencore-amrnb --disable-libopencore-amrwb --disable-libass --disable-libbs2b --disable-libcaca --disable-libcdio --disable-libcelt --disable-chromaprint --disable-libdc1394 --disable-debug --enable-htmlpages --disable-libebur128 --disable-libfdk-aac --enable-ffserver --disable-libflite --enable-fontconfig --enable-libfreetype --enable-frei0r --disable-libfribidi --disable-libgme --disable-libgsm --enable-iconv --disable-libilbc --disable-indev=jack --disable-libkvazaar --disable-ladspa --disable-libmp3lame --disable-libbluray --enable-mmx --disable-libmodplug --disable-netcdf --disable-openal --disable-indev=openal --disable-opencl --enable-libopencv --disable-opengl --disable-libopenh264 --disable-libopenjpeg --enable-optimizations --disable-libopus --disable-libpulse --disable-indev=pulse --disable-outdev=pulse --enable-runtime-cpudetect --disable-librubberband --enable-libschroedinger --disable-ffplay --disable-outdev=sdl --disable-sdl2 --disable-libsmbclient --disable-libsnappy --disable-indev=sndio --disable-outdev=sndio --disable-libsoxr --disable-libspeex --enable-sse --disable-libssh --disable-libtesseract --enable-libtheora --disable-libtwolame --enable-libv4l2 --enable-vaapi --enable-vdpau --disable-libvidstab --enable-libvorbis --disable-libvo-amrwbenc --enable-libvpx --disable-libwavpack --disable-libwebp --disable-x11grab --enable-libx264 --enable-libx265 --disable-libxcb --enable-libxvid --disable-outdev=xv --disable-libzimg --disable-libzmq --disable-libzvbi --disable-gcrypt --enable-gmp --disable-librtmp --enable-gnutls --disable-openssl --enable-version3 --disable-nonfree
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
[NULL @ 0x80c841400] Unable to find a suitable output format for '/dev/null'
/dev/null: Invalid argument

E: File read error
E: File read error
E: File read error
E: File read error
E: File read error
E: File read error
E: File read error
E: File read error
E: File read error

**Comment by achanler** [comment]
I think this showing up in the apache error log is a bug with the redirection to /dev/null in `admin/admin_sync.php`.

For example, running `ffmpeg 1>&2 /dev/null` produces the same `Unable to find a suitable output format for '/dev/null'
/dev/null: Invalid argument` message.

Fixing admin_sync.php file to run `ffmpeg >/dev/null 2>&1` stops the error message from showing up in the apache log, but i still cannot generate the video thumbnails.

Looking closer at the routine `check_ffmpeg` it checks the return code. Using `echo $?` after manually running ffmpeg with no options it returns 1.   Which should be treated as ffmpeg found.  I'm not sure why this routine is returning ffmpeg is not found.  I also tried adding the `-version` option to ffmpeg which causes its return code to be 0.  And that didn't work either.

**Comment by EddyLB** [comment]
I solved this issue by installing a fresh version of the 'true' [FFmpeg](http://www.ffmpeg.org) and updating Piwigo with this [fix](https://github.com/Piwigo/Piwigo/pull/756).
