### ISSUE TITLE
Does it auto-add videos/thumbs into the gallery?

### ISSUE THREAD

**Issue by jult** [Piwigo/piwigo-videojs#112]
Just asking, because I'm planning to use piwigo for a non stop feed of uploaded video files from security-cameras. Seems like a great idea, to have them in piwigo, but I'm not sure if this plugin would cause them to be added automatically when they're put into a folder.

Any ideas on this?

**Comment by EddyLB** [comment]
At the end of the upload, FFmpeg is automatically called to produce a video poster (thumbnail) and the video is added to the gallery with this thumbnail. The video is therefore immediately available but you may have to sync metadata manually to get them in full.

**Comment by jult** [comment]
But you have to manually upload the videos to a gallery of choice, This option is not available in most security cameras. They can upload to FTP-servers, or send mail.

**Comment by EddyLB** [comment]
Indeed, but extensions like [Photo from Email](http://piwigo.org/ext/extension_view.php?eid=813) or [Piwigo Import Tree](http://piwigo.org/ext/extension_view.php?eid=606) may allow to automatically upload photos.
