### ISSUE TITLE
Video Js Warnings

### ISSUE THREAD

**Issue by Gmessyhome** [Piwigo/piwigo-videojs#133]
21

Video JS Warnings and Notice

Hello/Hi/Greetings

Warning: array_merge(): Argument #1 is not an array in /var/www/html/piwigo/plugins/piwigo-videojs/admin/admin_sync.php on line 53

Notice: Undefined index: output in /var/www/html/piwigo/plugins/piwigo-videojs/admin/admin_sync.php on line 66

Warning: array_merge(): Argument #1 is not an array in /var/www/html/piwigo/plugins/piwigo-videojs/admin/admin_sync.php on line 78

All the boxs are green for FFmpeg etc etc

Tried looking for a solution , but after a while i started bashing head on the table.

Any help would be awesome as ever folks
FFmpeg version  ffmpeg version 3.4.2-2 Copyright (c) 2000-2018 the FFmpeg developers
ffprobe version 3.4.2-2 Copyright (c) 2007-2018 the FFmpeg developers
exiftool: /usr/bin/exiftool
MediaInfoLib - v17.12

Do i need to put the path in the boxs or having the green tick mean its installed and working ?

    Piwigo 2.9.4
    Operating system: Linux
    PHP: 7.2.7-0ubuntu0.18.04.2 (Show info) [2018-08-23 14:30:18]
    MySQL: 5.7.23-0ubuntu0.18.04.1 [2018-08-23 14:30:18]
    Graphics Library: ImageMagick 6.9.7-4

**Comment by jradwan** [comment]
Seems like the same problem as issue #130.

**Comment by Gmessyhome** [comment]
Solved the problem of the rror by unstalling the master file from Git. works perfect except for one issue

when i sysnc everything works fine and i get the desires result 


    file: ./galleries/Movies/test.mp4
    metadata: 15
    format, formatprofile, codecid, filesize, duration, playtime_seconds, bitrate, width, height, display_aspect_ratio,
    frame_rate, channel, sampling_rate, date_creation, type
    poster: ./galleries/Movies/pwg_representative/test.jpg

However the poster doesnt actually appear in the pwg_representive/test.jpg folder

**Comment by sfatula** [comment]
Your MySQL error is due to missing the creation date in the video metadata.
