### ISSUE TITLE
Unable to load template file (2.9.b)

### ISSUE THREAD

**Issue by boge90** [Piwigo/piwigo-videojs#134]
Hi,
I just upgraded the VideoJS plugin, and now I'm getting a error when I try to open a video.

The error I'm getting is:
Fatal error: Uncaught --> Smarty: Unable to load template file '/var/www/html/plugins/piwigo-videojs/template/vjs-player.tpl.v5' <-- thrown in /var/www/html/include/smarty/libs/sysplugins/smarty_internal_template.php on line 139

Piwigo version is: 2.9.4 (latest)

**Comment by frobozz-magic** [comment]
I get this too.  Running Piwigo 2.9.4 on Fedora 28 with latest updates.

**Comment by xbgmsharp** [comment]
It is fixed in the master branch. I will release a new version soon.

**Comment by xbgmsharp** [comment]
You might need to de-activate and re-activate the plugin as a few settings change

**Comment by boge90** [comment]
Thanks! that was quick.

I will keep looking for updates on my gallery.

**Comment by xbgmsharp** [comment]
Commit reference 
https://github.com/xbgmsharp/piwigo-videojs/commit/c7e23637817d0d9b39eb6c9e659632ef716a4300#diff-cb17f06dfa8c06d94b5ea75f6e84d4a0
