### ISSUE TITLE
videojs not generating thumbs under Docker environment

### ISSUE THREAD

**Issue by dantux** [Piwigo/piwigo-videojs#147]
I am running Piwigo with Docker (using linuxserver/piwigo image based on Alpine) and everything works fine, except the videojs. All seems OK, but when I try to generate thumbnails for the videos, the page just reloads without doing anything. 
I do have installed and working "mediainfo", "ffmpeg", "exiftool".
Any ideas what could be wrong? How can I troubleshoot this? Does "videojs" output some debug logs somewhere?

**Comment by dantux** [comment]
Update: I created a new Docker image with Ubuntu and apache. Unfortunately I am experiencing the same thing; everything works, except video-js does not generate the thumbs. It doesn't even create the pwg_representative folder. 
It is not a webserver permission issue, because at the command line (as webserver user) I can create files and folders in that directory. 
Anyone experienced this before?

**Comment by abrenoch** [comment]
I want to bump this. I'm seeing the same behavior on a Linux Mint install... Always worked well for me before so I'm not sure what has changed. Will try to get some logs.

**Comment by abrenoch** [comment]
See my comment here: https://github.com/xbgmsharp/piwigo-videojs/issues/141#issuecomment-469431038

Seems to be resolved for me now
