### ISSUE TITLE
 Warning: array_merge(): Argument #1 is not an array in /web/htdocs/www.fable.it/home/piwigo/plugins/piwigo-videojs/admin/admin_sync.php on line 53

### ISSUE THREAD

**Issue by fable** [Piwigo/piwigo-videojs#148]
Hello. 
I got the message in the title with my italian linux hosting site.
My provider hasn't medianfo and exiftool executable so I can't insert path in videojs plugin.
Is that a way for video Js work with only FFmpeg and ffprobe installed and inserted in the right line ? btw they disappear after the error in title.
Thank you.
![errore piwigo](https://user-images.githubusercontent.com/129857/51758140-4e8cb080-20c5-11e9-93a1-181507bdc49f.png)

**Comment by Danie10** [comment]
I have those paths active and working and also get an identical error:

Warning: array_merge(): Argument #1 is not an array in /home/danie/public_html/piwigo/plugins/piwigo-videojs/admin/admin_sync.php on line 53 Warning: Cannot modify header information - headers already sent by (output started at /home/danie/public_html/piwigo/plugins/piwigo-videojs/admin/admin_sync.php:53) in /home/danie/public_html/piwigo/include/page_header.php on line 101

**Comment by extorn** [comment]
5

Re: Video JS Warnings and Notice

Hi. For me, I resolved the issue by editing the offending file (admin_sync.php)

My changes are below in bold (note the existing code will mean that a corrupt run will prevent the plugin defaults being used to fill the gaps).

approx line 77 & 78 - replace the existing lines with this:
    // Merge default values with user submitted configuration (from webpage form)                   
    $sync_options = array_merge($sync_options, $sync_options_form);

**Comment by EddyLB** [comment]
Fixed the problem by replacing plugin files installed from the GUI with GitHub master source code and setting paths with LocalFiles Editor, e.g.:

> $conf['vjs_mediainfo_dir'] = '/srv/data/home/';
> $conf['vjs_exiftool_dir'] = '/srv/data/home/Image-ExifTool-11.11/';
> $conf['vjs_ffprobe_dir'] = '/srv/data/home/ffmpeg-4.0.2-64bit-static/';
> $conf['ffmpeg_dir'] = '/srv/data/home/ffmpeg-4.0.2-64bit-static/';

**Comment by georg90** [comment]
For me going back to version 2.8b helped. What could be the issue?

**Comment by nickbailey** [comment]
I see the following errors on a synchronisation with Piwigo 2.10.1 and VideoJS 2.9b
```
Warning: array_merge(): Expected parameter 1 to be an array, null given in /export/web/htdocs/piwigo/plugins/piwigo-videojs/admin/admin_sync.php on line 53

Warning: array_merge(): Expected parameter 1 to be an array, null given in /export/web/htdocs/piwigo/plugins/piwigo-videojs/admin/admin_sync.php on line 78
```
and have tried the fixes above without success.

Will 2.10 be released in time for Christmas? :)

**Comment by martin-0** [comment]
Had the same issue, git version fixed it.

**Comment by rafaelmaeuer** [comment]
Checkout: https://github.com/Piwigo/piwigo-videojs/issues/142#issuecomment-441487075
