### ISSUE TITLE
Add AVCHD (.MTS) support

### ISSUE THREAD

**Issue by tomchiverton** [Piwigo/piwigo-videojs#151]
If should be trivially possible e.g.  https://stackoverflow.com/a/25228716/466772

**Comment by EddyLB** [comment]
To ensure video playback in [browsers](https://caniuse.com/?search=video), we prefer to not allow the import of .mts, .mkv (https://github.com/Piwigo/piwigo-videojs/issues/199) or .mov (https://github.com/Piwigo/piwigo-videojs/pull/163) files.
