### ISSUE TITLE
Making another ffmpeg conversion

### ISSUE THREAD

**Issue by kajaba** [Piwigo/piwigo-videojs#158]
Hello
I would like to upload iphone videos (.mov). I will use ffmpeg for conversion and I need to execute ffmpeg conversion for example after thumbnail creation. But I cant seem to find the right place.

Where, on Earth, is the thumbnail created? Which php?
Thank you

**Comment by EddyLB** [comment]
Hi Kajaba,
Have you tried uploading videos with the Piwigo iOS app which will automatically convert the video into MP4? If the server if set properly, you will be able to produce the thumbnails from the web interface and play videos from the iOS app.
