### ISSUE TITLE
Does not recognize poster with .JPG extension 

### ISSUE THREAD

**Issue by truk39** [Piwigo/piwigo-videojs#159]
I recently updated to current versions of Piwigo and videojs. Our pwg_representative files are filled with files that end in .JPG (all caps). They will no longer display the poster. I noticed an older folder that had a few posters displaying, noticed .jpg extensions were lower case. Is there a way to get it to recognize the .JPG all caps?

**Comment by EddyLB** [comment]
Duplicate of https://github.com/Piwigo/Piwigo/issues/1171
