### ISSUE TITLE
Support for white space in files and folders

### ISSUE THREAD

**Issue by jfox00** [Piwigo/piwigo-videojs#16]
Is there any way I can customize the plugin so that it supports white spaces in files and folders, or can one of the developers add this?  I have thousands of photos and directories that have white spaces, and I do not want to change it.  I like the readability and the clarity.  I was able to get Piwigo proper to support white space and a couple of other special characters by using the Local Files Editor Plugin, and adding the following line to the local/config/config.inc.php file:

$conf['sync_chars_regex'] = '/^[a-zA-Z0-9-_. &,]+$/';

I have tested the sync from piwigo-videojs plugin, and it works fine when my folder and file had no white space (I ran a quick test), so I know that my ubuntu server is configured correctly.  Any help would be greatly appreciated!  Thanks again, and keep up the amazing work.

**Comment by rolfen** [comment]
So why do we still not have support for spaces 9 years later?
