### ISSUE TITLE
Video size larger than window size

### ISSUE THREAD

**Issue by adadnc** [Piwigo/piwigo-videojs#165]
I'm facing a problem when opening a page with a video. The video is much larger than the window and it does not adapt to the window (see attached screenshot).

![Screenshot from 2020-06-04 11-02-46](https://user-images.githubusercontent.com/40058694/83737236-04b9c000-a653-11ea-95c0-1bf803e816f8.png)
The behavior changes with different themes but the base problem having the video occupy larger area than the screen stays with all of them.
Also, I used Video.js V5, V6 and V7 with same behavior.

**Comment by adadnc** [comment]
Just see that it works for Video.js V4, but not the other versions.

**Comment by abrenoch** [comment]
This appears to happen because the plugin injects some CSS that is formatted based on the video dimensions.

Seems like `.my_video_1-dimensions.vjs-fluid` Should have a maximum value of 100%. Might even be preferable to make it configurable.

**Comment by yarez0** [comment]
same problem for years, have to use native browser for landscape, in portrait got to view in full screen. trying to open an issue but never got a respond

**Comment by adadnc** [comment]
With version 11.1.0 piwigo-videojs doesn't work at all anymore

**Comment by EddyLB** [comment]
It works with Piwigo 11 but you have to install it manually.

**Comment by adadnc** [comment]
> It works with Piwigo 11 but you have to install it manually.

You are not going to tell us details, are you?

**Comment by EddyLB** [comment]
Here is a selection of URLs:

https://github.com/Piwigo/Piwigo-Mobile/wiki

https://piwigo.org/forum/viewtopic.php?id=31197

https://piwigo.org/forum/viewtopic.php?id=30858

https://piwigo.org/forum/viewtopic.php?id=29250

**Comment by adadnc** [comment]
> Here is a selection of URLs:
> 
> https://github.com/Piwigo/Piwigo-Mobile/wiki
> 
> https://piwigo.org/forum/viewtopic.php?id=31197
> 
> https://piwigo.org/forum/viewtopic.php?id=30858
> 
> https://piwigo.org/forum/viewtopic.php?id=29250

I'm sorry, but non of these links describe how to install it manually.

**Comment by EddyLB** [comment]
There is a page explaining how to install Piwigo [manually](https://piwigo.org/doc/doku.php?id=user_documentation:learn:install:installation_manual). To summarise, the procedure consists in uploading by FTP the Piwigo folder to the server.

For plugins, you follow the same route. You download the VideoJS plugin from [GitHub](https://github.com/Piwigo/piwigo-videojs). Then, you upload the "piwigo-videojs-master" folder to the server and place it inside the "plugins" folder located inside the "piwigo" folder of your server. Rename it "piwigo-videojs".

You then login as admin, go to Administration / Plugins and activate the VideoJS plugin. The rest is explained in the already provided URLs. 

To display the video at a size which fits well into the browser's window, I use the "Native Browser" option in Player (don't use one of the Video.js players if you don't want to face the problem described by this issue).
