### ISSUE TITLE
metadata sync fails - ffprobe does not properly parse longitude tag from mp4 video

### ISSUE THREAD

**Issue by sock3t** [Piwigo/piwigo-videojs#167]
Hi folks,

I am running into an issue when importing videos into piwigo:

From caddy / Batch Manager I pick a newly added video and and choose "Videos" from the "Action" dropdown menu.

Once I klick on "Apply Action" almost all of the operations succeed (like poster creation, film effect, thumbnail(s) creation). But the metadata sync fails and I get this error message:
```
truncated for column 'longitude' at row 1
UPDATE piwigo_images SET `filesize`='46299', `width`='1920', `height`='1080', `latitude`='+50.0994', `longitude`='+008.5446/', `date_creation`='2019-04-15 19:47:16', `date_metadata_update`=CURDATE() WHERE `id`=177114; in /var/www/piwigo/include/dblayer/functions_mysqli.inc.php on line 856

Warning: Cannot modify header information - headers already sent by (output started at /var/www/piwigo/include/dblayer/functions_mysqli.inc.php:855) in /var/www/piwigo/include/page_header.php on line 86
```
I guess the 3rd line is just a victim of the stuff failing above.

The smoking gun seems to be the trailing slash here: `'longitude'='+008.5446/',` 

When I google the error message of the first line: "truncated for column ..." this indicates that we tried to insert a string into a DB column which does not match with the columns allowed data type or length.

So my guess is that the trailing slash is the bad guy here. Yet I can't explain where this comes from. Exiftool does not show anything suspicious about the GPS tags of that file:

```Location Information            : (none) Role=shooting Lat=50.09949 Lon=8.54459 Alt=0.00 Body=earth Notes=
GPS Latitude                    : 50 deg 5' 58.16" N
GPS Latitude Ref                : North
GPS Longitude                   : 8 deg 32' 40.52" E
GPS Longitude Ref               : East
```

    Piwigo 2.10.2 Check for upgrade
    Operating system: Linux
    PHP: 7.0.33-0+deb9u6 (Show info) [2020-09-01 23:42:59]
    MySQL: 5.5.5-10.3.23-MariaDB-0+deb10u1 [2020-09-01 23:42:59]
    Graphics Library: GD 2.2.4

**Comment by sock3t** [comment]
Just found one more hint in apache error.log:

```
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    location        : +50.0994+008.5446/
    location-eng    : +50.0994+008.5446/
    encoder         : Lavf58.20.100
    Stream #0:0(eng): Video: png, rgb24, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 60 fps, 60 tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2019-04-15T17:47:16.000000Z
      handler_name    : VideoHandle
      encoder         : Lavc58.35.100 png
```
This is output from ffmpeg while it is extracting the poster as well as the thumbnails.
ffprobe shows the same output. 

I tried the same on a video which does not experience this issue (from a different camera) and this does not list any location information via ffprobe:
```
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2020-08-22T13:42:28.000000Z
    encoder         : Lavf58.20.100
```

So my assumption so far is that VideoJs will fall back to exiftool or mediainfo for this file and then get a proper location tag.

Update: mediainfo does not return any GPS tags for any of my video files (tested a handfull).

To test my assumption: Is there a way to force VideoJs to use exiftool only?

**Comment by sock3t** [comment]
OK, I renamed both ffprobe & mediainfo binaries on my system and tried to import the video again - success!

Import returns a large block in green with all successful generated poster + thumbs + metadata sync.
Two yellow lines complaining:
```
    Metadata parsing disable because mediainfo is not installed on the system, eg: '/usr/bin/mediainfo'.
    Metadata parsing disable because ffprobe is not installed on the system, eg: '/usr/bin/ffprobe'.
```
Which is expected.

It would still be very helpful to know how to force VideoJs to use exiftoll only. The hack to rename the other binaries migth break other plugins or processes on the same server!

Or ideally fix the parsing of GPS tags from ffprobe so it does not choke on the trailing slash.

**Comment by martins250** [comment]
It has been a long time since the last entry here, but I am glad I tracked it down (and the solution) since I came across exactly the same problem with the / at the end of the longitude. It would be good if it could be fixed.

I was a little worried about renaming ffprobe and mediainfo binaries on my server just in case I forgot about it and they were needed at some later date. However I was happy just to delete the gps location metadata and found a solution on [https://unix.stackexchange.com/questions/339119/how-to-strip-gps-location-data-from-an-mp4-video-file](https://unix.stackexchange.com/questions/339119/how-to-strip-gps-location-data-from-an-mp4-video-file), which I repeat as:

`ffmpeg -i input.mp4 -metadata location="" -metadata location-eng="" -acodec copy -vcodec copy output.mp4`

The video is then synchronised in the VideoJS plugin without any problems.

**Comment by chrud** [comment]
Seems like a well-placed rtrim() should do the trick...
In include/ffprobe.php:

```
{
   $gps = (string)$general['tags']['location'];
   $value = preg_split('/(\+|\-)/', $gps, -1, PREG_SPLIT_DELIM_CAPTURE);
   $exif['latitude'] = $value[1].$value[2];
   $exif['longitude'] = $value[3].rtrim($value[4],'/');
}
```

-chrud
