### ISSUE TITLE
Not Compatible with Piwigo 11.1.0

### ISSUE THREAD

**Issue by jasondickerson** [Piwigo/piwigo-videojs#171]
I really like this plugin and would like to continue using it post Piwigo 11.0+ upgrade.  

Thanks!

**Comment by mz5555** [comment]
+1

**Comment by yarez0** [comment]
please

**Comment by xbgmsharp** [comment]
Not sure what is need. But feel free to do so. I will be happy to accept PR.

**Comment by yarez0** [comment]
this plugin is dead.. 3 years without commit

**Comment by efelon** [comment]
After I manually installed it and tested many functions with piwigo 11.3, I'm pretty positive that it is just a matter of marking the plugin compatible in the piwigo extensions page somehow: https://piwigo.org/ext/extension_view.php?eid=610
I have never done such thing, so maybe @xbgmsharp you could have a look there?!

I compared the functionality with piwigo 2.10.2:
* playback with Video.js v5
* sync from plugin settings
* sync from batch manager
* poster creation w/wo overlay

**Comment by Fedena22** [comment]
Hey there, 
I played all little around with the settings and when I had the player set to video.js vx my existing videos won't play and are only static. 
When I changed the player to Native Browser my existing videos would work again  
Still the settings page is broken in the sync tab. 

Maybe that helps to keep your existing videos playing.

**Comment by v-marinkov** [comment]
Is there any consensus on this? Is it safe to update to Piwigo 11.4.0?

**Comment by plegall** [comment]
We're using version 2.7.a on Piwigo.com for Piwigo 11.4.0. Working fine.

**Comment by yarez0** [comment]
Yep. Still works. There are some bugs (huge overlay in portrait mode) but if you use native browser it’s fine. Hope someone upgrade this plugin or make a fork with 2021 functions

**Comment by v-marinkov** [comment]
Great! Is any functionality lost when using PIwigo 11?

**Comment by yarez0** [comment]
Can’t sync more than 10 videos in the same time in my config (nginx 500 error)

**Comment by yarez0** [comment]
my bad, error 405 on more than 5 videos
