### ISSUE TITLE
ffmpeg not accessible // Nginx Webserver Docker-Compose // mount ffmpeg directory

### ISSUE THREAD

**Issue by Daniel-WW** [Piwigo/piwigo-videojs#178]
Hi,

my Piwigo photogallery is running on a Synology NAS within a Docker-Environment.
More exactly, MariaDB, php7 and a NGINX Webserver are running as docker containers and enable thus the installation of piwigo.

Ffmpeg is installed as a package on the Synology NAS OS.

Over the docker-compose file I mounted the ffmpeg-directory into the NGINX Webserver container, to make it reachable for the VideoJS plugin. 

```
...
   volumes:
     - /usr/bin/ffmpeg:/usr/bin/ffmpeg
...
```

I'm not shure if this is correct because Video-JS plugin still couldn't find ffmpeg.

What else do I need to consider to get VideoJS running?
Do I have to adjust the nginx conf-files?
Or is there a bettter way to make ffmpeg accessible for VideoJS?

I'm a verry newbie in server stuff like this. So I would be verry thankful for every kind of help or advice. - If it's helpful, i can provide more information or code. Pleas ask me. 

Thanks for your help in advance. Best regards - Daniel

**Comment by EddyLB** [comment]
Please complete the installation as explained [here](https://github.com/Piwigo/piwigo-videojs/blob/master/README.md).
