### ISSUE TITLE
Unsupported operand types

### ISSUE THREAD

**Issue by adonix-dev** [Piwigo/piwigo-videojs#179]
Hi, 

I got an issue when accessing the VideoJS tab of a video.
![image](https://user-images.githubusercontent.com/31833518/140233084-f428b307-6297-4a81-8806-53ef2041c19e.png)

PHP Page says : ./admin.php?page=plugin&section=piwigo-videojs/admin/admin_photo.php&image_id=74
`Fatal error: Uncaught Error: Unsupported operand types in /var/www/html/piwigo/plugins/piwigo-videojs/include/exiftool.php:58 Stack trace: #0 /var/www/html/piwigo/plugins/piwigo-videojs/admin/admin_photo.php(109): include() #1 /var/www/html/piwigo/admin/plugin.php(53): include_once('/var/www/html/p...') #2 /var/www/html/piwigo/admin.php(298): include('/var/www/html/p...') #3 {main} thrown in /var/www/html/piwigo/plugins/piwigo-videojs/include/exiftool.php on line 58`

**Comment by flth** [comment]
easy fix for this.
open plugins/piwigo-videojs/include/exiftool.php, go to line 58 which looks like
`$exif['duration'] = round($general['Duration']*1000, 0);`
and replace it with
`$exif['duration'] = round((int)$general['Duration']*1000, 0);`

tested with Piwigo 12.2.0 and PHP 8.0

**Comment by RenaeMacLeod** [comment]
This worked for me, thanks! Just need to work around the read-only nature of my directories.
