### ISSUE TITLE
Video does not play

### ISSUE THREAD

**Issue by tomchiverton** [Piwigo/piwigo-videojs#186]
https://rachaelandtom.info/photos/picture/19161-pxl_20220722_211046611/category/816-groove_armada
https://rachaelandtom.info/photos/picture/19220-pxl_20220722_224651329/category/813-07

Audio plays, no video.

As far as I can tell, all installed fine, and neither of the two trouble shooting things in the Wiki seem to apply - MIME is OK.

Seems to effect all .mp4 files. "mp4file --optimize" has no effect.

I can't tell if this is a FireFox issue or not...

Directly linking to https://rachaelandtom.info/photos/galleries/falken-random/Phone-Photos/2022/07/PXL_20220722_224651329.mp4 (813-07 above) has the same issue - no video, audio only.

BUT if I download it, vlc plays it fine.

**Comment by nugget210** [comment]
I'm getting exactly the same issue, doesn't seem to matter which browser I use.  

I've also tried changing the player in the plugin settings to each of the Video.js.v4 to Video.js.v7 and also tried the native browser option. I get the same result with any of the five options - no video, only audio.

**Comment by kg333** [comment]
Issue persists for MP4 videos under version 13.8.0.  #207 appears related.

**Comment by nugget210** [comment]
Yeah I still have issues on any browser.  Luckily the PiwigoNG app seems to play videos perfectly, which is handy.  Hopefully the browser issue gets resolved at some stage.

Appreciate all of your hard work devs!

**Comment by EddyLB** [comment]
@tomchiverton , @nuggets and @kg333 , do you still encounter this issue with the version 15.c?

**Comment by kg333** [comment]
My issues track with the findings on #227 and either play normally or don't play at all, so unrelated after all to the "audio plays, no video" issue described here.

**Comment by tomchiverton** [comment]
Still broken.

https://rachaelandtom.info/photos/picture/22297-pxl_20220722_211046611/search/psk-20241106-9qbJFkFA0a

says "no video with supported format and MIME type found."

The thumbnail visible behind this is correct.

Direct link to the MP4, same.

VLC is fine with it once downloaded.

```
falken@frame:~/Desktop$ file PXL_20220722_211046611.mp4; ls -laht PXL_20220722_211046611.mp4 
PXL_20220722_211046611.mp4: ISO Media, MP4 Base Media v1 [ISO 14496-12:2003]
-rw-rw-r-- 1 falken falken 29M Nov  6 11:19 PXL_20220722_211046611.mp4
falken@frame:~/Desktop$ 


```

**Comment by EddyLB** [comment]
Hi @tomchiverton, Safari 18.1 plays [your video](https://rachaelandtom.info/photos/galleries/falken-random/Phone-Photos/2022/07/PXL_20220722_224651329.mp4) without problem but Firefox 132.0.1 returns the error "No video with supported format and MIME type found". 
I have downloaded it and discovered that the video track is encoded with the HEVC format which is not supported by most browsers as you can read [here](https://caniuse.com/?search=video). The extension of the file should be .hevc, not .mp4.
I close this issue because it is not related to the plugin.
