### ISSUE TITLE
admin_sync php fatal error

### ISSUE THREAD

**Issue by grantiago** [Piwigo/piwigo-videojs#189]
Hi I am hoping to run this plugin in piwigo 13x. I am getting the following errors:
`Warning: Undefined array key "vjs_sync" in /mnt/tera/www/piwi/plugins/piwigo-videojs/admin/admin_sync.php on line 78`
`PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #1 must be of type array, bool given in `
`/www/piwi/plugins/piwigo-videojs/admin/admin_sync.php:78`

- Environment
- [Piwigo](https://piwigo.org/) 13.1.0
- Installed on 7 May 2022, 5 months 3 weeks 3 days ago
- Operating system: Linux
- PHP: 8.0.25
- MySQL: 8.0.31-0ubuntu0.20.04.1 [2022-11-01 11:31:45]
- Graphics Library: External ImageMagick 6.9.10-23
- Cache size 5.58 Mo   calculated 24 minutes ago Refresh
-  Activated plugin list2
- LocalFiles Editor
- VideoJS

**Comment by grantiago** [comment]
I initially installed this plugin using the piwigo admin page. I compared  admin_sync.php in this repo and at the file installed on my server. They are quite different. I uploaded a copy of this repository file of admin_sync.php The plugin is now working with some additional errors I will post in another issue. Thanks

**Comment by jesta030** [comment]
Hey I got the same problem, copying admin_sync.php lets me start the sync but it doesn't appear to be working. Any tips?
