### ISSUE TITLE
Warning: Undefined array key "resolution"

### ISSUE THREAD

**Issue by grantiago** [Piwigo/piwigo-videojs#190]
`Resolution : Warning: Undefined array key "resolution" in`
`www/piwi/_data/templates_c/p6jhns^ac333712a269e008e144927ad231641d8a730a58_0.file.admin_config.tpl.php on line 268
/> Yes ` 
`Warning: Undefined array key "resolution" in /mnt/tera/www/piwi/_data/templates_c/p6jhns^ac333712a269e008e144927ad231641d8a730a58_0.file.admin_config.tpl.php on line 270
checked="checked"/> No`

Environment
[Piwigo](https://piwigo.org/) 13.1.0
Installed on 7 May 2022, 5 months 3 weeks 3 days ago
Operating system: Linux
PHP: 8.0.25
MySQL: 8.0.31-0ubuntu0.20.04.1 [2022-11-01 11:31:45]
Graphics Library: External ImageMagick 6.9.10-23
Cache size 5.58 Mo   calculated 24 minutes ago Refresh
Activated plugin list2
LocalFiles Editor
VideoJS

**Comment by jesta030** [comment]
Same error here after upgrading to piwigo 13.3.0. VideoJS config page says:

> Warning: Undefined array key "resolution" in /config/www/_data/templates_c/8cpdn4^8a06367f9fa423b9dc2c475f9b6592b413a100c7_0.file.admin_config.tpl.php on line 268
> /> Ja Warning: Undefined array key "resolution" in /config/www/_data/templates_c/8cpdn4^8a06367f9fa423b9dc2c475f9b6592b413a100c7_0.file.admin_config.tpl.php on line 270
> checked="checked"/> Nein
> RESOLUTION_DESC

When syncing it produces an error:

> Warning: Undefined array key "vjs_sync" in /config/www/plugins/piwigo-videojs/admin/admin_sync.php on line 78
> 
> Fatal error: Uncaught TypeError: array_merge(): Argument #1 must be of type array, bool given in /config/www/plugins/piwigo-videojs/admin/admin_sync.php:78 Stack trace: #0 /config/www/plugins/piwigo-videojs/admin/admin_sync.php(78): array_merge() #1 /config/www/plugins/piwigo-videojs/admin/admin.php(68): include_once('...') #2 /app/www/public/admin/plugin.php(53): include_once('...') #3 /app/www/public/admin.php(316): include('...') #4 {main} thrown in /config/www/plugins/piwigo-videojs/admin/admin_sync.php on line 78

Piwigo 13.3.0
Installiert auf 10 Dezember 2022, vor 1 Tag
Betriebssystem: Linux
PHP: 8.0.26
MySQL: 10.6.10-MariaDB-log [2022-12-11 21:12:52]
Grafikbibliothek: ImageMagick 7.1.0-50
Größe des Cache nicht vorhanden   nie berechnet

**Comment by BrianO10** [comment]
Greetings,
After upgrading to 13.3.0, I am experiencing the same issue:

Resolution : Warning: Undefined array key "resolution" in /home/xxxx/yyyy.com/Piwigo/_data/templates_c/p6jhns^2621e737be51e2299804169ce9565ca6ee0203aa_0.file.admin_config.tpl.php on line 268
/> Yes Warning: Undefined array key "resolution" in /home/xxxx/yyyy.com/Piwigo/_data/templates_c/p6jhns^2621e737be51e2299804169ce9565ca6ee0203aa_0.file.admin_config.tpl.php on line 270
checked="checked"/> No

Thanks,
Brian

**Comment by Compunologist** [comment]
I'm noticing the same erroneous behavior here after a fresh install of 13.4.0:

Resolution : Warning: Undefined array key "resolution" in /config/www/_data/templates_c/p6jhns^b6abb1d84350daf359dafd4908d870913a76b342_0.file.admin_config.tpl.php on line 268
/> Yes Warning: Undefined array key "resolution" in /config/www/_data/templates_c/p6jhns^b6abb1d84350daf359dafd4908d870913a76b342_0.file.admin_config.tpl.php on line 270
checked="checked"/> No

Piwigo 13.4.0
Installed on 29 December 2022, 1 day ago
Operating system: Linux
PHP: 8.0.26
MySQL: 10.10.2-MariaDB-1:10.10.2+maria~ubu2204
Graphics Library: ImageMagick 7.1.0-50

Activated plugin list
Exif View
Fotorama
LocalFiles Editor
OpenStreetMap
VideoJS

**Comment by eekay35** [comment]
These same errors continue with Piwigo 13.5.0, unfortunately.

**Comment by tanty** [comment]
Same here with piwigo 13.6.0 from [linuxserver.io](https://docs.linuxserver.io/images/docker-piwigo)

**Comment by Dechinta** [comment]
Well, it is hard to believe that this error is still around. 
The template comes from .../plugins/piwigo-videojs/admin/admin_config.tpl' as mentioned in the description.

The error comes from the fact that the array "resolution" is not defined.
Each time you save the configuration it rewrites the template. No matter what you do on the template, it will be rewritten. Therefore, we need to modify the piwigo-videojs/admin/admin_config.tpl file, right? No!

Resolution array is defined its the piwigo-videojs/admin/admin_config.php file.

So, on line 96 add:
							'resolution'    => get_boolean($_POST['vjs_resolution']),

Then everything is solved...

Voila...

**Comment by grantiago** [comment]
@Dechinta
> 
> Resolution array is defined its the piwigo-videojs/admin/admin_config.php file.
> 
> So, on line 96 add: 'resolution' => get_boolean($_POST['vjs_resolution']),
> 
> Then everything is solved...
> 
> Voila...

Fixed it for me thank you.
