### ISSUE TITLE
Unable to upload video files

### ISSUE THREAD

**Issue by sesipod** [Piwigo/piwigo-videojs#193]
Piwigo - Verison 13
VideoJS installed and enabled and I have also added the required items to the config file. I still cannot upload MOV or MP4 files to the site. Photos work just fine. 

![Screen Shot 2022-12-06 at 7 14 00 PM](https://user-images.githubusercontent.com/1533744/206063460-d13893cb-bc01-4de8-8f81-9b172e2152ff.png)
![Screen Shot 2022-12-06 at 7 14 27 PM](https://user-images.githubusercontent.com/1533744/206063536-3d1d5453-2f6e-44d0-976e-d6a6cce8bb34.png)
![Screen Shot 2022-12-06 at 7 14 38 PM](https://user-images.githubusercontent.com/1533744/206063580-67dec24c-9b3e-4eb2-88d1-4fd8186d64a7.png)

**Comment by yogapilatesPPM** [comment]
same issue for me

**Comment by n0hot** [comment]
I have this issue also.

**Comment by EddyLB** [comment]
Have you tried to add the following lines to LocalFiles Editor / Local Config (see e.g. [here](https://github.com/Piwigo/Piwigo-Mobile/wiki/Configure-Piwigo-for-Uploading-Videos)):

```
$conf['picture_ext'] = array('jpg','jpeg','png','gif','tif','tiff');
$conf['file_ext'] = array_merge(
  $conf['picture_ext'],
  array('mp4','m4v','mpg','ogg','ogv','webm','webmv')
  );
```

I strongly recommend to NOT add the .MOV format which is not managed by most web browsers.

**Comment by deysumitkr** [comment]
Have you tried to set `$conf['upload_form_all_types'] = true;`:

```// in the upload form, let users upload only picture_exts or all file_exts?
// for some file types, Piwigo will try to generate a pwg_representative
// (TIFF, videos, PDF)
$conf['upload_form_all_types'] = true;
```

Ref: https://piwigo.org/forum/viewtopic.php?pid=183400#p183400
