### ISSUE TITLE
my_video_1 width =0

### ISSUE THREAD

**Issue by vadimkim** [Piwigo/piwigo-videojs#20]
I don't know why, but {$WIDTH} parameter at vjs-player.tpl file has value = 0 during runtime. It makes window to shrink to 0 size. There is no problem with {$HEIGHT}. It has default value of 480px. 
I have hard-coded width = 720px in these 2 lines:
<div style="margin: 0 auto; width:720px; min-width:480px">
<video id="my_video_1" class="video-js {/literal}{$VIDEOJS_SKIN}{literal}" {/literal}{$OPTIONS}{literal} width={/literal}"720"{literal} height={/literal}"{$HEIGHT}"{literal} poster={/literal}"{$VIDEOJS_POSTER_URL}"{literal} data-setup='{}'>

Please, check if this a bug?

**Comment by EddyLB** [comment]
In the absence of feedback, considered fixed.
