### ISSUE TITLE
No video posters

### ISSUE THREAD

**Issue by brentkearney** [Piwigo/piwigo-videojs#201]
Hello,

I am running Piwigo 13.6.0 from the [linuxserver docker image](https://hub.docker.com/r/linuxserver/piwigo), and the piwigo-videojs plugin from the master branch. I tried first with the one installed from the Piwigo admin interface.

Video poster images are being generated properly for me - the jpgs appear in the pwg_representative sub-directories, but they are not displayed on the web. Using Web Inspector in my browser, the image being displayed instead is:

`img src="../../themes/default/icon/errors_small.png"`

I read that the latest bootstrap_darkroom had been updated to work with videojs, so switched to that, but no difference for me. I also tried cloning the theme from Github and replacing themes/bootstrap_darkroom, to make sure I had the latest code. The SmartPocket theme is disabled. I have confirmed that the video poster jpgs exist in their respective pwg_representative directories, and have global read permissions on both files and directories.

I have these plugins installed & active:
* Community
* LocalFiles Editor
* Security Headers
* ShareAlbum
* VideoJS

This warning message appears in the VideoJS Settings, under the "Resolution" setting:

```
Warning: Undefined array key "resolution" in /config/www/_data/templates_c/p6jhns^b6abb1d84350daf359dafd4908d870913a76b342_0.file.admin_config.tpl.php on line 268
```
I have neither Yes nor No selected in that section. I see no errors in any of the logs. 

I have tried synchronizing in Tools and with the VideoJS plugin settings, as well as the various options under Tools -> Maintenance, and nothing seems to make a difference for the video posters.

Any advice for getting the video poster/thumbnails to display would be much appreciated. 🙏

**Comment by tanty** [comment]
> This warning message appears in the VideoJS Settings, under the "Resolution" setting:
> 
> ```
> Warning: Undefined array key "resolution" in /config/www/_data/templates_c/p6jhns^b6abb1d84350daf359dafd4908d870913a76b342_0.file.admin_config.tpl.php on line 268
> ```
> 
> I have neither Yes nor No selected in that section. I see no errors in any of the logs.

Check #190

**Comment by EddyLB** [comment]
Fixed with https://github.com/Piwigo/piwigo-videojs/pull/229
