### ISSUE TITLE
Installation of VideoJS Plugin with Piwigo

### ISSUE THREAD

**Issue by kdmiller45** [Piwigo/piwigo-videojs#203]
Using Ubuntu 22,04.1 LTS
Piwigo 13.6.0

I get the following errors

 Warning: Undefined array key "resolution" in /var/www/html/piwigo/_data/templates_c/p6jhns^c8391e2f331fc4daec99f78d1dae3a438f4968c9_0.file.admin_config.tpl.php on line 268
/> Yes Warning: Undefined array key "resolution" in /var/www/html/piwigo/_data/templates_c/p6jhns^c8391e2f331fc4daec99f78d1dae3a438f4968c9_0.file.admin_config.tpl.php on line 270
checked="checked"/> No

any help would be great

**Comment by Tianqi2020** [comment]
https://github.com/Piwigo/piwigo-videojs/pull/202

The issue has been fixed in this request but no one approve it. If you follow the change in this pull and save your change in the videojs setting once more. The error goes away.

**Comment by Tianqi2020** [comment]
FYI, you can find more disscussion here.

https://github.com/Piwigo/piwigo-videojs/issues/190

**Comment by kdmiller45** [comment]
next I found these errors 

Resolution : Warning: Undefined array key "resolution" in /var/www/html/piwigo/_data/templates_c/p6jhns^c8391e2f331fc4daec99f78d1dae3a438f4968c9_0.file.admin_config.tpl.php on line 268
/> Yes Warning: Undefined array key "resolution" in /var/www/html/piwigo/_data/templates_c/p6jhns^c8391e2f331fc4daec99f78d1dae3a438f4968c9_0.file.admin_config.tpl.php on line 270
checked="checked"/> No

**Comment by EddyLB** [comment]
Fixed with https://github.com/Piwigo/piwigo-videojs/pull/229
