### ISSUE TITLE
Playback problem 8K video / Samsung S22 Videos

### ISSUE THREAD

**Issue by RalfKraemer1** [Piwigo/piwigo-videojs#207]
Hello, I can upload videos from my Samsung S22 mobile phone in 8K/24 Fps without any problems. But unfortunately only the sound is played in the gallery. Only the preview image of the video appears.

Codec: MPEG-H Part2/HEVC (H.265) (hvc1)
[Videoresolution: 7680x4320](resolution: 7680x4320)
Codec: MPEG AAC Audio (mp4a)
codecid: mp42
format: MP4
formatprofile: Base Media / Version 2
sampling_rate: 48000
type: video/mp4

Everything else works fine

**Comment by EddyLB** [comment]
Only a very few browsers support the HEVC H.265 codec. See e.g. [here](https://caniuse.com/?search=video). 
This issue is not related with the plugin.
