### ISSUE TITLE
XML library is missing to use mediainfo 

### ISSUE THREAD

**Issue by Rneil-ca** [Piwigo/piwigo-videojs#208]
Recently upgraded Piwigo from version 12 to 13, lost all my videos in the database when doing this upgrade.  Now if I try and sync a director I get the following Warning no matter what I select and it does not see any videos.:

XML library is missing to use mediainfo   

I am currently running Piwigo 13.7.0 and I am running the the latest Piwigo-videojs from Git.    Also running latest MediaInfo: MediaInfoLib - v21.09

Not sure what to do to fix this, but I have a large database and dont want to mess it all up.  

Ryan

**Comment by xbgmsharp** [comment]
From the code, it seem you are missing the php-xml library. the code use the function SimpleXMLElement to parse the XML file.
https://github.com/Piwigo/piwigo-videojs/blob/7c4a2186b773a57f7904298ea479cf55e3266691/include/function_dependencies.php#L35
