### ISSUE TITLE
sync breaks on short videos

### ISSUE THREAD

**Issue by outdoorbits** [Piwigo/piwigo-videojs#214]
If videos are shorter than the time set to create the poster, the sync breaks completely. Could this error been catched? Maybe sync could try to get an image at second 0 or use a standard image.

`Warning: imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error: Empty input file in /www/piwigo/plugins/piwigo-videojs/include/function_frame.php on line 56

Warning: imagecreatefromjpeg(): "./galleries/Archiv/2023/2023-05-21/pwg_representative/20230521_164755.jpg" is not a valid JPEG file in /www/piwigo/plugins/piwigo-videojs/include/function_frame.php on line 56

Fatal error: Uncaught TypeError: imagesx(): Argument #1 ($image) must be of type GdImage, bool given in /www/piwigo/plugins/piwigo-videojs/include/function_frame.php:70 Stack trace: #0 /www/piwigo/plugins/piwigo-videojs/include/function_frame.php(70): imagesx() #1 /www/piwigo/plugins/piwigo-videojs/include/function_sync2.php(193): add_movie_frame() #2 /www/piwigo/plugins/piwigo-videojs/admin/admin_sync.php(140): require_once('...') #3 /www/piwigo/plugins/piwigo-videojs/admin/admin.php(68): include_once('...') #4 /www/piwigo/admin/plugin.php(53): include_once('...') #5 /www/piwigo/admin.php(345): include('...') #6 {main} thrown in /www/piwigo/plugins/piwigo-videojs/include/function_frame.php on line 70`

**Comment by EddyLB** [comment]
Fixed with https://github.com/Piwigo/piwigo-videojs/pull/229
