### ISSUE TITLE
Upload video "unsupported format"

### ISSUE THREAD

**Issue by sapycola** [Piwigo/piwigo-videojs#215]
Hi,
i have installad videoJs.
my Localfile:

$conf['upload_form_all_types'] = true;
$conf['sync_chars_regex'] = '/^[a-zA-Z0-9-_. ]+$/';
$conf['show_exif'] = true;
$conf['show_exif_fields'] = array(
  'Make',
  'Model',
  'ExifVersion',
  'Software',
  'DateTimeOriginal',
  'FNumber',
  'ExposureBiasValue',
  'FILE;FileSize',
  'ExposureTime',
  'Flash',
  'ISOSpeedRatings',
  'FocalLength',
  'FocalLengthIn35mmFilm',
  'WhiteBalance',
  'ExposureMode',
  'MeteringMode',
  'ExposureProgram',
  'LightSource',
  'Contrast',
  'Saturation',
  'Sharpness',
  'bitrate',
  'channel',
  'date_creation',
  'display_aspect_ratio',
  'duration',
  'filesize',
  'format',
  'formatprofile',
  'codecid',
  'frame_rate',
  'latitude',
  'longitude',
  'make',
  'model',
  'playtime_seconds',
  'sampling_rate',
  'type',
  'resolution',
  'rotation',
  );

But it's impossibile to load a file video .mp4, i try to add extension: 'mp4' but not work to upload it.

**Comment by deysumitkr** [comment]
Have you tried to set `$conf['upload_form_all_types'] = true;`?
```
// for some file types, Piwigo will try to generate a pwg_representative
// (TIFF, videos, PDF)
$conf['upload_form_all_types'] = true;
```
Ref: https://piwigo.org/forum/viewtopic.php?pid=183400#p183400

**Comment by EddyLB** [comment]
Please see [this page](https://github.com/Piwigo/Piwigo-Mobile/wiki/Configure-Piwigo-for-Uploading-Videos).
