### ISSUE TITLE
Warning: Undefined array key "resolution"

### ISSUE THREAD

**Issue by Groofertje** [Piwigo/piwigo-videojs#217]
Environment
[Piwigo](https://piwigo.org/) 14
Installed on 21 Dec 2023
Operating system: Debian GNU/Linux 12 (bookworm)
VideoJS

[Warning: Undefined array key "resolution" in /mnt/DataDisk/www/public/piwigo/_data/templates_c/p6jhns^692b93885e2371fdf3d39260b560f744055a947d_0.file.admin_config.tpl.php on line 268](https://duckduckgo.com/?q=Warning%3A+Undefined+array+key+%22resolution%22+in+%2Fmnt%2FDataDisk%2Fwww%2Fpublic%2Fpiwigo%2F_data%2Ftemplates_c%2Fp6jhns%5E692b93885e2371fdf3d39260b560f744055a947d_0.file.admin_config.tpl.php+on+line+268&atb=v376-1&t=chromentp&ia=web)

**Comment by leonkiriliuk** [comment]
Here's how I fixed it on Debian 12 with Piwigo 14
The Piwigo team really needs to take over this plugin and own it. Not supporting video in 2023 is a crime; videos at this point are as important as images!

1) Start with the most up-to-date repo: https://github.com/klaoun/piwigo-videojs
- click CODE and download as zip
- replace all the files in piwigo/plugins/piwigo-videojs with that content

2) Fix deprecated float to int casting:
- edit include/function_frame.php and modify these lines at about the end of the file:

```
  // add source to band
  imagecopy($imgBand, $srcImage, (int)3*$const, (int)(3/2)*$const, 0, 0, (int)$srcWidth, (int)$srcHeight);
```

and this:

```
/**
 * create a rectangle with round corners
 * http://www.php.net/manual/fr/function.imagefilledrectangle.php#42815
 */
function imagefilledroundrectangle(&$img, $x1, $y1, $x2, $y2, $color, $radius)
{ 
  imagefilledrectangle($img, (int)$x1+$radius, (int)$y1, (int)$x2-$radius, (int)$y2, (int)$color);

  if ($radius > 0)
  {
    imagefilledrectangle($img, (int)$x1, (int)$y1+$radius, (int)$x2, (int)$y2-$radius, (int)$color);
    imagefilledellipse($img, (int)$x1+$radius, (int)$y1+$radius, (int)$radius*2, (int)$radius*2, (int)$color);
    imagefilledellipse($img, (int)$x2-$radius, (int)$y1+$radius, (int)$radius*2, (int)$radius*2, (int)$color);
    imagefilledellipse($img, (int)$x1+$radius, (int)$y2-$radius, (int)$radius*2, (int)$radius*2, (int)$color);
    imagefilledellipse($img, (int)$x2-$radius, (int)$y2-$radius, (int)$radius*2, (int)$radius*2, (int)$color);
  }
}
```
3) If you want to add iPhone video support (MOV files) apply the following code changes as well:

[https://github.com/Piwigo/piwigo-videojs/pull/163](url)

Good luck!

**Comment by Groofertje** [comment]
Tx for the answer, my grandchildren will be happy if it works. 🙂
________________________________
Van: Leon Kiriliuk ***@***.***>
Verzonden: vrijdag 22 december 2023 20:12
Aan: Piwigo/piwigo-videojs ***@***.***>
CC: Guillaume Swennen ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Piwigo/piwigo-videojs] Warning: Undefined array key "resolution" (Issue #217)


Here's how I fixed it on Debian 12 with Piwigo 14
The Piwigo team really needs to take over this plugin and own it. Not supporting video in 2023 is a crime; videos at this point are as important as images!

  1.  Start with the most up-to-date repo: https://github.com/klaoun/piwigo-videojs

  *   click CODE and download as zip
  *   replace all the files in piwigo/plugins/piwigo-videojs with that content

  1.  Fix deprecated float to int casting:

  *   edit include/function_frame.php and modify these lines at about the end of the file:

  // add source to band
  imagecopy($imgBand, $srcImage, (int)3*$const, (int)(3/2)*$const, 0, 0, (int)$srcWidth, (int)$srcHeight);


and this:

/**
 * create a rectangle with round corners
 * http://www.php.net/manual/fr/function.imagefilledrectangle.php#42815
 */
function imagefilledroundrectangle(&$img, $x1, $y1, $x2, $y2, $color, $radius)
{
  imagefilledrectangle($img, (int)$x1+$radius, (int)$y1, (int)$x2-$radius, (int)$y2, (int)$color);

  if ($radius > 0)
  {
    imagefilledrectangle($img, (int)$x1, (int)$y1+$radius, (int)$x2, (int)$y2-$radius, (int)$color);
    imagefilledellipse($img, (int)$x1+$radius, (int)$y1+$radius, (int)$radius*2, (int)$radius*2, (int)$color);
    imagefilledellipse($img, (int)$x2-$radius, (int)$y1+$radius, (int)$radius*2, (int)$radius*2, (int)$color);
    imagefilledellipse($img, (int)$x1+$radius, (int)$y2-$radius, (int)$radius*2, (int)$radius*2, (int)$color);
    imagefilledellipse($img, (int)$x2-$radius, (int)$y2-$radius, (int)$radius*2, (int)$radius*2, (int)$color);
  }
}


  1.  If you want to add iPhone video support (MOV files) apply the following code changes as well:

https://github.com/Piwigo/piwigo-videojs/pull/163<url>

Good luck!

**Comment by EddyLB** [comment]
Fixed with https://github.com/Piwigo/piwigo-videojs/pull/229
