### ISSUE TITLE
Playing video+audio OK on PC, KO on piwigo NG Android app.

### ISSUE THREAD

**Issue by Fabien-35235** [Piwigo/piwigo-videojs#221]
Hi.
I have mp4 video on my piwigo site, with the videoJs plugin.

Video files play correctly on windows and linux with firefox and chrome
on Android, chrome is OK, firefox does not play the audio, but plays correctly the video.
on Android app (piwigo NG), the app hangs over video playing

JPG files works perfectly , on any linux/windows/android browser  and on the Android app.

Video are generated with ffmpeg:
ffmpeg -i input input.mp4 \
        -loglevel error \
        -movflags +faststart \
        -c:v libx264 \
        -profile:v high \
        -c:a aac \
        -pix_fmt yuvj420p \
        -metadata author="Author name" \
        -metadata copyright="(C) author 2024" \
        -metadata comment="Some comment" \
        output.mp4

(see https://ffmpeg.org/ffmpeg-formats.html fragmentation for movflags, this SHOULD be equivalent to mp4file --optimize )
(I had problems with 4:2:2 video not playing, moving them to 4:2:0 solved the issue)

Video files have a jpg pwg_representative, which has thumbnails, and are seen correctly by the android app as video.

So, this looks like an unsupported audio/video format.
Any hint on what could be wrong, or appropriate ffmpeg flags to try?

The following attempts did not change the behavior:
 - change audio codec to libfdk_aac, 
 - change the audio bitrate and sampling frequency, 
 - change the AVC profile to 'main' 
 - set -preset slow

Thanks for your help

Config:
piwigo 14.1.0 with videoJS, running on synology NAS
piwigo NG 2.2.3 Android running on Android 11, 8GB RAM.
Fabien.

**Comment by Fabien-35235** [comment]
On Android, viewing video+audio with firefox is OK, BRAVE is KO for audio. So the audio problem seems to be an Android Brave issue, not related to this thread.

**Comment by EddyLB** [comment]
Indeed, not related to this thread.
