### ISSUE TITLE
Error on Synchronization of metadata information and poster creation

### ISSUE THREAD

**Issue by ElGatoFlojo** [Piwigo/piwigo-videojs#222]
I get an error when trying to sync:

Warning: Undefined array key "vjs_sync" in /mnt/WORK/_WEB/Images/plugins/piwigo-videojs/admin/admin_sync.php on line 78 Deprecated: unserialize(): Passing null to parameter #1 ($data) of type string is deprecated in /mnt/WORK/_WEB/Images/plugins/piwigo-videojs/admin/admin_sync.php on line 78 Fatal error: Uncaught TypeError: array_merge(): Argument #1 must be of type array, bool given in /mnt/WORK/_WEB/Images/plugins/piwigo-videojs/admin/admin_sync.php:78 Stack trace: #0 /mnt/WORK/_WEB/Images/plugins/piwigo-videojs/admin/admin_sync.php(78): array_merge(false, Array) #1 /mnt/WORK/_WEB/Images/plugins/piwigo-videojs/admin/admin.php(68): include_once('/mnt/WORK/_WEB/...') #2 /mnt/WORK/_WEB/Images/admin/plugin.php(53): include_once('/mnt/WORK/_WEB/...') #3 /mnt/WORK/_WEB/Images/admin.php(346): include('/mnt/WORK/_WEB/...') #4 {main} thrown in /mnt/WORK/_WEB/Images/plugins/piwigo-videojs/admin/admin_sync.php on line 78

Piwigo 14.3.0 
OS: FreeBSD
PHP: 8.2.8 
MySQL: 10.5.21-MariaDB

**Comment by marfig2005** [comment]
Hello, I have the same issue
Piwigo 14.3.0
PHP: 8.2.5 
MySQL: 10.11.2-MariaDB

**Comment by EddyLB** [comment]
Do you still get this warning with version 15.c?

**Comment by marfig2005** [comment]
with 15.c version it disappeared, but the video itself does not appear in the browser, when the visitor clicks on the thumbnail in the gallery, an error pages opens with 
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 293338120 bytes) in /volume1/web/include/functions_picture.inc.php on line 146

Should I create a new issue for it?

**Comment by EddyLB** [comment]
Thank you for your reply.
I guess the problem you encounter is [this one](https://github.com/Piwigo/Piwigo/issues/2239).
