### ISSUE TITLE
Thumbnail not display

### ISSUE THREAD

**Issue by Fancham** [Piwigo/piwigo-videojs#226]
Hi, 

I have installed Piwigo Version 14.4.0 and VideoJS 2.9b and I can watch my videos on Piwigo but no thumbnails are displayed in the gallery. I have checked in videos folder, I found pwg_representative with jpg with same name as mp4. All seems OK but no thumbnails are generated when I synchronize. I have this message :
Synchronization results
6 video(s) selected
6 video(s) with metadata added
6 poster(s) created
0 thumbnail(s) created
0 warnings during synchronization
0 erreurs survenues durant la synchronisation

Thanks for your help.

Regards

**Comment by EddyLB** [comment]
From your post, I see that the plugin has produced 6 posters (probably jpg files), i.e. one thumbnail per video stored in the `upload/…/pwg_representative` folder, which is fine. The mentioned '0 thumbnail(s)' are those created every x seconds for a VideoJS player. If you use the native player of your browser (recommended today), you do not need them.

Your Piwigo should automatically produce thumbnails from each poster in the _data/i/upload/…/pwg_representative folder (depends on sizes selected in Configuration / Photos sizes). If this is not the case, check the line corresponding to each video in the `…_images` table of your database. The attribute `representative_ext` should contain `jpg` to tell Piwigo that a representative exists in the `upload/…/pwg_representative` folder.

**Comment by EddyLB** [comment]
Fixed with version 15.d (1b9e19b4bd837ca1c2c46e86bcbf05d86a2635c5) which introduces a synchronization option to adopt downloaded posters.
