### ISSUE TITLE
Piwigo no displaying or playing Videos.

### ISSUE THREAD

**Issue by MintyMcMintface** [Piwigo/piwigo-videojs#227]
Hi All,

I write to raise a noob question.  Apologies if there is a thread for this but I have been searching online for sometime and don't have a answer.

I run Linux Mint 21.3 Cinnamon as a server for documents, I run Piwigo on it in order to get my photos away from the google monster.  

I have .htaccess files in my mounted drives. My photo directory (./galleries) has my photos drive mounted as a sym-link (bind) to my Piwigo directory.

Photos work fine.

Videos, do not load.  All are MP4, All work outside of Piwigo, just not inside Piwigo. 

If I upload new videos they work fine.  It's just the ones I synced.  

I have followed the directions here: https://github.com/Piwigo/piwigo-videojs/wiki/How-to-add-videos#external-tools

I have added the config lines.  

I am sure I am doing something wrong, but I can't figure it out.  

What information would be useful to provide to help with finding out why my video's don't play. 

One other thing, I get the following error: "The media could not be loaded, either because the server or network failed or because the format is not supported"

I also get a check sum "error: 0" when trying to validate checksum.

**THINGS I HAVE TRIED:**  

- Converting videos to MP4 265 and 265 formats and reloading/re-syncing.

- Adding these lines to the .htaaccess files:  

AddType video/ogg .ogv
AddType video/mp4 .mp4
AddType video/webm .webm

- I get a error when running these but have ffmpg etal:  

 # apt-get install ffmpeg
 # wget http://mediaarea.net/download/binary/mediainfo/0.7.74/mediainfo_0.7.74-1_amd64.Debian_7.0.deb
 # wget http://mediaarea.net/download/binary/libmediainfo0/0.7.74/libmediainfo0_0.7.74-1_amd64.Debian_7.0.deb
 # wget http://mediaarea.net/download/binary/libzen0/0.4.31/libzen0_0.4.31-1_amd64.Debian_7.0.deb
 # dpkg -i libzen0_0.4.31-1_amd64.Debian_7.0.deb libmediainfo0_0.7.74-1_amd64.Debian_7.0.deb  mediainfo_0.7.74-1_amd64.Debian_7.0.deb

- Converting videos and re-sync.

Anybody have any ideas?

**Comment by EddyLB** [comment]
This is not the right place to ask such questions. Please use the [Piwigo forums](https://piwigo.org/forum/index.php) and provide Piwigo and server logs, the LocalFiles Editor configuration (see e.g. [here](https://github.com/Piwigo/Piwigo-Mobile/wiki/Configure-Piwigo-for-Uploading-Videos)) and report on the manual use of `ffmpeg` and `mediainfo`.

**Comment by kg333** [comment]
@EddyLB , if this isn't the correct venue for support of issues with VideoJS, Piwigo should probably talk to the plug-in author and ask them to point to the Piwigo forums.  Their plug-in settings page is directing users here:
![image](https://github.com/user-attachments/assets/e449bfd7-4ec9-42ea-b777-2b40220115c7)

I'm having the same problem and followed the link to the VideoJS Github issue page.

**Comment by EddyLB** [comment]
The error "The media could not be loaded, either because the server or network failed or because the format is not supported" is returned by a VideoJS player. Have you tried with the native player of your browser?

**Comment by kg333** [comment]
> The error "The media could not be loaded, either because the server or network failed or because the format is not supported" is returned by a VideoJS player. Have you tried with the native player of your browser?

Disabling the VideoJS plugin results in Piwigo presenting a static video for any uploaded images by default.  Clicking Photo Sizes->Original results in the below error ("No video with supported format and MIME type found").  Attempting the same on the earlier videos that do play successfully _does_ work.  Browser is Firefox 132.0.  

Examining a failing video and a playing video, the key difference appears to be that videos that work for me are h264 encoding, while failing videos are h265/HEVC.  Based on the VideoJS issue listed [here](https://github.com/videojs/video.js/issues/6889), h265 just isn't going to work unless the native browser supports it, which Firefox does not.  As the final nail in the coffin, switching off VideoJS and loading one of the offending videos in Chrome works fine: Chrome does support h265.

Based on that, I'd recommend closing this.  There's nothing Piwigo or VideoJS can do to add h265 without browser support.

Firefox native playback
![image](https://github.com/user-attachments/assets/46dd1217-de8d-4350-b2da-994b68101cd1)

Working video codec
![image](https://github.com/user-attachments/assets/98428183-94ed-408a-aca3-c7000f4589a9)

Failing video codec
![image](https://github.com/user-attachments/assets/18288871-1aa4-4587-8810-3fb63632b8cf)

**Comment by EddyLB** [comment]
Thanks for your reply.
Yes, the [compatibility of browsers with videos](https://caniuse.com/?search=video) is quite limited. 
This is also the reason why we preferred to not allow the import of .mkv (https://github.com/Piwigo/piwigo-videojs/issues/199) or .mov (https://github.com/Piwigo/piwigo-videojs/pull/163) files.
