### ISSUE TITLE
Error displayed in settings

### ISSUE THREAD

**Issue by geoffschultz** [Piwigo/piwigo-videojs#228]
When I go into settings, the following error is displayed 2 times at the bottom next to Resolution:

Undefined array key "resolution" in /usr/www/users/gschultz/GeoffSchultz/photos/_data/templates_c/p6jhns^63f255208313cab78df34cbd591aff9dc2fcf8fd_0.file.admin_config.tpl.php on line 268

I'm running a clean install of Piwigo 14.5 on FreeBSD.

**Comment by EddyLB** [comment]
Fixed with https://github.com/Piwigo/piwigo-videojs/pull/229
