### ISSUE TITLE
Can not upload a non-16:9 video to Piwigo from the piwigo-lightroom plugin...

### ISSUE THREAD

**Issue by Film54** [Piwigo/piwigo-videojs#230]
Using the publish setting in the Lightroom Piwigo plug in, 16x9 videos will upload fine.  Using the piwigo web interface, non-16x9 videos upload and play fine... but when trying to upload videos that are not of standard size from doing a Lightroom sync via piwigo-lightroom the videos will not upload and give me an error "upload failed".  Any help for fixing would be greatly appreciated!  Thank you.

**Comment by EddyLB** [comment]
Hello @Film54 
Do I understand well that the problem you encounter is related with the upload of videos with the lightroom plugin, not the retrieval of metadata, the creation of thumbnails or watching videos?

If yes, I invite you to submit your questions on the forum thread dedicated to the [lightroom plugin](https://piwigo.org/forum/viewtopic.php?id=16629&p=23)?
