### ISSUE TITLE
Warning after syncing mp4 files and trying to create posters: Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by ebnels** [Piwigo/piwigo-videojs#235]
Everytime I try to create mp4 posters on files I've uploaded, I get the following error message: Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/piwigo/plugins/piwigo-videojs/include/function_caller.php:48) in /var/www/html/piwigo/include/page_header.php on line 99. 

When I scroll down, I see the warning: Poster and Thumbnail creation disable because FFmpeg is not installed on the system, eg: '/usr/bin/ffmpeg'. FFmpeg is installed and in /usr/bin and defined in config.inc.php. I'm using piwigo 15.0 and piwigo-videojs 15b.

Any help in resolving this would be appreciated.

**Comment by jradwan** [comment]
Seems similar to issue reported here: https://piwigo.org/forum/viewtopic.php?pid=191003#p191003

Something is wrong with the code that is trying to locate ffmpeg/mediainfo/ffprobe, etc. This started when I upgraded to v15.b after Piwigo 15 was released.
