### ISSUE TITLE
remote_sync.pl not including videojs sync

### ISSUE THREAD

**Issue by TheFozid** [Piwigo/piwigo-videojs#238]
Hi all

I have a script running on a cron job, that syncs the database for all the pictures and videos, but it fails to generate the thumbnails/posters for the videos. I have to manually go into the web page to do the videojs sync. I am using the included piwigo script remote_sync.pl

**Comment by TheFozid** [comment]
Resolved by creating a new remote_sync.pl file to carry out the poster gen automatically

**Comment by EddyLB** [comment]
Ok, thanks.
