### ISSUE TITLE
Windows ffmpeg issue

### ISSUE THREAD

**Issue by TooSpeedy** [Piwigo/piwigo-videojs#239]
Having issues generating the thumbnails, ffmpeg is installed and calls fine from cmd (im hosting this on a Windows Server on IIS). 

The following comes up in the log

```
[2024-11-15 22:51:43]	[DEBUG]	exec(ffmpeg -version >NUL 2>NUL) returns "", retval: 1
[2024-11-15 22:51:43]	[DEBUG]	ERROR: Calling ffmpeg did fail.
```

in the readme is says about having to add a couple of lines on Linux but there was nothing for Windows. Is there somethig specific i need to do?

```
 //   2. on Linux: make ffmpeg and ffprobe executable with:
    //      > chmod +x ffmpeg
    //      > chmod +x ffprobe
    //   3. check it with e.g. './ffmpeg -version' on Linux
    $conf['vjs_ffprobe_dir'] = '/home/clients/.../ffmpeg/ffmpag-7.1/';
    $conf['vjs_ffmpeg_dir'] = '/home/clients/.../ffmpeg/ffmpag-7.1/';
```

**Comment by EddyLB** [comment]
Hi @TooSpeedy 
Use LocalFiles Edition to provide the path required to execute ´ffmpeg'. Replace ´/home/clients/.../ffmpeg/ffmpag-7.1/´ of the Linux example with the path required on your server, e.g. something like: ´C:\Program Files\Git\FFmpeg\´.

**Comment by TooSpeedy** [comment]
This issue can be closed. The bit that needs to be set is in the ApplicationPool for that site, "Load User Profile" was initially set to false, once i changed this to true it started working fine.

**Comment by EddyLB** [comment]
Thanks.
